apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  namespace: ml-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
      - name: collector
        image: freshinit/metrics-collector:latest
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: metrics-data-pvc
---        
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-data-pvc
  namespace: ml-pipeline
spec:
  volumeName:  metrics-exporter-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
