prometheus:
  prometheusSpec:
    # 1. Persist the TSDB to a PVC
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-data
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

    # 2. Retain 30d of data (override default 15d)
    retention: "30d"

    # 3. Standard scrape interval
    scrapeInterval: "30s"

    # 4. Discover ServiceMonitors in every namespace
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}

# Make sure you collect node-level metrics
nodeExporter:
  enabled: true

# And Kubernetes object & container metrics
kubeStateMetrics:
  enabled: true

# Your existing extra audit-exporter monitor
kubeEtcd:
  service:
    enabled: true
    port: 2379
    targetPort: 2379
  serviceMonitor:
    enabled: true
    namespace: kube-system
    interval: 30s
  additionalServiceMonitors:
    - name: kube-audit-exporter
      namespace: monitoring
      selector:
        matchLabels:
          app: kube-audit-exporter
      endpoints:
        - port: metrics
          path: /metrics
          interval: 30s

# === Control-plane scrapes over HTTPS ===
kubeApiserver:
  enabled: true
  serviceMonitor:
    https: true
    path: /metrics
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true

kubeControllerManager:
  enabled: true
  serviceMonitor:
    https: true
    path: /metrics
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true

kubeScheduler:
  enabled: true
  serviceMonitor:
    https: true
    path: /metrics
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true

# === HTTP-only scrapes ===
kubeProxy:
  enabled: true
  serviceMonitor:
    https: false
    path: /metrics
    scheme: http

coredns:
  enabled: true
  serviceMonitor:
    https: false
    path: /metrics
    scheme: http

# === etcd (sidecar on API server) ===
etcd:
  enabled: true
  serviceMonitor:
    https: true
    path: /metrics
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
      