apiVersion: audit.k8s.io/v1
kind: Policy
# Log only metadata (user, verb, resource, timestamp) for all requests:
rules:
  - level: Metadata
    resources:
      - group: ""        # core API group
        resources: ["pods", "secrets", "configmaps", "namespaces"]
  # If you want full request/response bodies for certain verbs on critical resources:
  - level: RequestResponse
    verbs: ["create", "delete", "update"]
    resources:
      - group: ""        # core API group
        resources: ["secrets"]
  # Default rule (if no other matches): don’t log
  - level: None