---
# Java
openjdk_pkg_name: "openjdk-{{ java_major_version }}-jre"
java_major_version: 21

# Jenkins
jenkins_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
jenkins_key_dest: "/etc/apt/keyrings/jenkins-keyring.asc"
jenkins_repo_url: "https://pkg.jenkins.io/debian-stable"
jenkins_repo_components: "binary/"
jenkins_pkg_name: "jenkins"