---
# Java
openjdk_pkg_name: "openjdk-{{ java_major_version }}-jre"
java_major_version: 21

# Jenkins
jenkins_key_url: "https://pkg.jenkins.io/debian/jenkins.io-2023.key"
jenkins_key_dest: "/etc/apt/keyrings/jenkins-keyring.asc"
jenkins_repo_url: "https://pkg.jenkins.io/debian"
jenkins_repo_components: "binary/"
jenkins_pkg_name: "jenkins"
letsencrypt_email: "emmanuelaladejana05@gmail.com"
jenkins_token_name: "k8s-automated-dr"
git_repo_url: "https://github.com/Janortop5/k8s-automated-dr.git"
jenkins_live_domain: "jenkins.{{ jenkins_public_ip }}.nip.io"  ## this is temporary for testing purposes

# Iterate over every suffix until Cerbot succeeds
public_suffixes:
  - nip.io
  - sslip.io
  - traefik.me


