---
# Tasks for building and pushing Docker image

- name: Build Docker image
  community.docker.docker_image:
    name: "{{ docker_registry }}/{{ docker_image_name }}"
    build:
      path: "{{ pipeline_dir }}"
      pull: yes
    source: build
    tag: "{{ docker_image_tag }}"
    push: false
  
- name: Push Docker image
  community.docker.docker_image:
    name: "{{ docker_registry }}/{{ docker_image_name }}:{{ docker_image_tag }}"
    push: true
  when: push_image | bool