---
# 0) Prereqs: make sure yq (Go binary) and yamllint are available
- name: Ensure yq v4 and yamllint are installed
  apt:
    name:
      - curl        # to fetch yq
      - yamllint
    state: present
    update_cache: yes
  become: true

- name: Download Mike Farah’s yq v4 if not present
  get_url:
    url: https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_linux_amd64
    dest: /usr/local/bin/yq
    mode: '0755'
  become: true

# 1) Make sure our audit log dir & policy file exist
- name: Create audit log directory
  file:
    path: /var/log/kubernetes/audit
    state: directory
    mode: '0700'
  become: true

- name: Copy audit policy to control-plane
  copy:
    src: k8s-metrics-data/audit-policy.yaml
    dest: /etc/kubernetes/audit-policy.yaml
    owner: root
    group: root
    mode: '0644'
  become: true

# 2) Ensure the manifest begins with a YAML document start
- name: Ensure '---' at top of kube-apiserver manifest
  lineinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    line: '---'
    insertafter: BOF
    state: present
  become: true

###################################################
# 3) Ensure Python3 and pip exist (dist-agnostic) #
###################################################
- name: Remove existing audit-policy mount
  command: >
    yq eval -i '
      with(.spec.containers[] | select(.name=="kube-apiserver");
        .volumeMounts |= map(select(.name!="audit-policy"))
      )
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  ignore_errors: true
  become: true

- name: Remove existing audit-logs mount
  command: >
    yq eval -i '
      with(.spec.containers[] | select(.name=="kube-apiserver");
        .volumeMounts |= map(select(.name!="audit-logs"))
      )
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  ignore_errors: true
  become: true

- name: Remove existing audit-policy volume
  command: >
    yq eval -i '
      .spec.volumes |= map(select(.name!="audit-policy"))
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  ignore_errors: true
  become: true

- name: Remove existing audit-logs volume
  command: >
    yq eval -i '
      .spec.volumes |= map(select(.name!="audit-logs"))
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  ignore_errors: true
  become: true

- name: Remove any existing audit mounts
  command: >
    yq eval -i '
      with(.spec.containers[] | select(.name=="kube-apiserver");
        .volumeMounts |= (unique_by(.name))
      )
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true

- name: Ensure audit log file exists
  file:
    path: /var/log/kubernetes/audit/audit.log
    state: touch
    owner: root
    group: root
    mode: '0640'
  become: true

- name: Add --audit-log-path and --audit-policy-file to kube-apiserver args
  command: >
    yq eval -i '
      (.spec.containers[] | select(.name=="kube-apiserver") .command)
        += ["--audit-log-path=/var/log/kubernetes/audit/audit.log",
            "--audit-policy-file=/etc/kubernetes/audit-policy.yaml"]
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true
  notify: Restart kubelet
#######################################################

#######################################################
# 4) Insert the four audit blocks structurally via yq #
#######################################################
- name: Add audit-policy mount to kube-apiserver
  command: >
    yq eval -i '
      (.spec.containers[] | select(.name=="kube-apiserver") .volumeMounts) +=
      [{"name":"audit-policy",
        "mountPath":"/etc/kubernetes/audit-policy.yaml",
        "readOnly":true}]
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true
  notify: Restart kubelet

- name: Add audit-logs mount to kube-apiserver
  command: >
    yq eval -i '
      (.spec.containers[] | select(.name=="kube-apiserver") .volumeMounts) +=
      [{"name":"audit-logs",
        "mountPath":"/var/log/kubernetes/audit",
        "readOnly":false}]
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true
  notify: Restart kubelet

- name: Add audit-policy volume to kube-apiserver
  command: >
    yq eval -i '
      .spec.volumes +=
      [{"name":"audit-policy",
        "hostPath":{"path":"/etc/kubernetes/audit-policy.yaml","type":"FileOrCreate"}}]
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true
  notify: Restart kubelet

- name: Add audit-logs volume to kube-apiserver
  command: >
    yq eval -i '
      .spec.volumes +=
      [{"name":"audit-logs",
        "hostPath":{"path":"/var/log/kubernetes/audit","type":"DirectoryOrCreate"}}]
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true
  notify: Restart kubelet
##########################################################

##########################################################
# 5) Lint the resulting manifest (80-char rule disabled) #
##########################################################
- name: Lint kube-apiserver manifest (ignore line-length)
  command: >
    yamllint
      -d "{extends: default, rules: {line-length: disable}}"
      --strict --format parsable
      /etc/kubernetes/manifests/kube-apiserver.yaml
  register: lint_result
  failed_when: lint_result.rc != 0
  changed_when: false
  become: true
##############################################################################

##############################################################################
# 6) If lint passed, restart kubelet so API server picks up the new manifest #
##############################################################################
- name: Restart kubelet to apply new kube-apiserver manifest
  service:
    name: kubelet
    state: restarted
  become: true
###################################################

###################################################
#  Ensure Python3 and pip exist (dist-agnostic)   #
###################################################
- name: Install python3 & pip on master
  become: true
  package:
    name:
      - python3
      - python3-pip
  when:
    - "'master-node' in group_names"
    - ansible_pkg_mgr == "apt"

- name: Install python3 & pip on master (Yum/RHEL/Amazon Linux)
  become: true
  package:
    name:
      - python3
      - python3-pip
  when:
    - "'master-node' in group_names"
    - ansible_pkg_mgr == "yum"

- name: Install Kubernetes Python client (pip3)
  become: true
  pip:
    name: kubernetes==27.2.0
    executable: pip3
  when: "'master-node' in group_names"
#######################################################################

#######################################################################
# Jenkins namespace / SA / RBAC  +  kube-config for the plugin.       #
#######################################################################
# 0) Make sure the namespace exists
- name: Namespace jenkins (idempotent)
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: jenkins
    state: present
  environment: { KUBECONFIG: /etc/kubernetes/admin.conf }
  when: "'master-node' in group_names"

# 1) ServiceAccount for the agents
- name: ServiceAccount jenkins-agent
  kubernetes.core.k8s:
    api_version: v1
    kind: ServiceAccount
    name: jenkins-agent
    namespace: jenkins
    state: present
  environment: { KUBECONFIG: /etc/kubernetes/admin.conf }

# 2) Cluster-admin binding (wide-open but simple)
- name: Bind SA to cluster-admin
  kubernetes.core.k8s:
    definition:                 # ← inline manifest (NOT template/src)
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: jenkins-agent-admin
      subjects:
        - kind: ServiceAccount
          name: jenkins-agent
          namespace: jenkins
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
    state: present
  environment: { KUBECONFIG: /etc/kubernetes/admin.conf }
  when: "'master-node' in group_names"

# 3) Mint a short-lived (24 h) token for Jenkins
- name: Create 24-h token for the SA
  command: kubectl create token jenkins-agent -n jenkins --duration=24h
  register: jenkins_token_cmd
  environment: { KUBECONFIG: /etc/kubernetes/admin.conf }
  when: "'master-node' in group_names"

# 4) Grab the cluster CA (already base64)
- name: Read cluster CA
  slurp:
    src: /etc/kubernetes/pki/ca.crt
  register: k8s_ca
  when: "'master-node' in group_names"

# 5) Stash facts we’ll need to write the kube-config
- set_fact:
    jenkins_token: "{{ jenkins_token_cmd.stdout }}"
    jenkins_ca_b64: "{{ k8s_ca.content }}"
  when: "'master-node' in group_names"

# 6) Emit kube-config on the *control* host
- name: Write kube-config for Jenkins
  copy:
    dest: "{{ playbook_dir }}/jenkins-kubeconfig.yaml"
    mode: '0600'
    content: |
      apiVersion: v1
      kind: Config
      clusters:
      - name: kubernetes
        cluster:
          server: https://{{ master_private_ip }}:6443
          certificate-authority-data: {{ jenkins_ca_b64 }}
      users:
      - name: jenkins
        user:
          token: "{{ jenkins_token }}"
      contexts:
      - name: jenkins@kubernetes
        context:
          cluster: kubernetes
          user: jenkins
          namespace: jenkins
      current-context: jenkins@kubernetes
  delegate_to: localhost
  run_once: true
  become: false
  when: "'master-node' in group_names"

# 7) Tell the operator where it is
- name: Show kube-config path + Jenkins hints
  debug:
    msg: |
      -----------------------------------------------------------------
      Saved kubeconfig to:  {{ playbook_dir }}/jenkins-kubeconfig.yaml

      In **Jenkins → Manage Credentials** add it as:
        • Kind: *Kubernetes configuration (kubeconfig)*
        • File : jenkins-kubeconfig.yaml
        • ID   : k8s-jenkins-agent (for example)

      Then in **Manage Nodes and Clouds → Kubernetes Cloud**:
        • Kubernetes URL : https://{{ master_private_ip }}:6443
        • Credentials    : k8s-jenkins-agent
        • Namespace      : jenkins
      -----------------------------------------------------------------
  run_once: true
#######################################################################
