---
- name: Update APT cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Install fontconfig and OpenJDK JRE
  apt:
    name:
      - fontconfig
      - "{{ openjdk_pkg_name }}"
    state: present

- name: Verify Java version
  command: java -version
  register: java_version
  changed_when: false

- name: Show Java version output
  debug:
    msg: "{{ java_version.stderr_lines }}"

- name: Ensure APT keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Download Jenkins signing key
  get_url:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    dest: /etc/apt/keyrings/jenkins-keyring.asc
    mode: 0644

- name: Add Jenkins weekly APT repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
    filename: jenkins-weekly
    state: present
    update_cache: yes

- name: Install Jenkins
  apt:
    name: "{{ jenkins_pkg_name }}"
    state: latest
    update_cache: yes
  register: jenkins_pkg
  
- name: Ensure Jenkins service is started
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins to be up (HTTP 200 on /login)
  uri:
    url: "http://localhost:8080/login"
    status_code: 200
  register: jenkins_up
  retries: 12
  delay: 10
  until: jenkins_up.status == 200
