---
- name: Wait for API server to be reachable
  wait_for:
    host: "{{ hostvars[groups['master-node'][0]].ansible_default_ipv4.address }}"
    port: 6443
    state: started
    timeout: 300

- name: "Check whether this node is already registered"
  ansible.builtin.command: >
    kubectl get node {{ inventory_hostname }}
      --kubeconfig /home/{{ ansible_user }}/.kube/config
  register: node_check
  failed_when: false
  changed_when: false
  delegate_to: "{{ groups['master-node'][0] }}"

- name: Cleanup any partial kubeadm state
  become: true
  ansible.builtin.shell: |
    kubeadm reset -f
    rm -rf /etc/kubernetes/pki \
            /etc/kubernetes/kubelet.conf \
            /etc/kubernetes/bootstrap-kubelet.conf \
            /etc/kubernetes/admin.conf \
            /var/lib/etcd \
            /var/lib/kubelet/*
  ignore_errors: true
  when: node_check.rc != 0

- name: "Join the Kubernetes cluster"
  ansible.builtin.shell: >
    {{ hostvars[groups['master-node'][0]].join_command }}
    --apiserver-advertise-address={{ hostvars[groups['master-node'][0]].ansible_default_ipv4.address }}
    --ignore-preflight-errors=all
  become: true
  when: node_check.rc != 0
