---
# 1) Ensure audit log directory exists
- name: Create audit log directory
  file:
    path: /var/log/kubernetes/audit
    state: directory
    mode: '0700'

# 2) Copy your audit policy
- name: Copy audit policy to control-plane
  copy:
    src: audit-policy.yaml
    dest: /etc/kubernetes/audit-policy.yaml
    owner: root
    group: root
    mode: '0644'

# 3) Inject all audit flags under the "command:" section
- name: Enable audit logging flags in kube-apiserver manifest
  blockinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    marker: "# {mark} ANSIBLE AUDIT FLAGS"
    insertafter: 'command:'
    block: |
      - --audit-policy-file=/etc/kubernetes/audit-policy.yaml
      - --audit-log-path=/var/log/kubernetes/audit/audit.log
      - --audit-log-maxage=30
      - --audit-log-maxbackup=10
      - --audit-log-maxsize=100
  notify: Restart kubelet

# 4) Mount the audit directory into the API-server container
- name: Mount audit directory in kube-apiserver
  blockinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    marker: "# {mark} ANSIBLE AUDIT VOLUME MOUNTS"
    insertafter: 'volumeMounts:'
    block: |
      - name: audit-logs
        mountPath: /var/log/kubernetes/audit
        readOnly: false

# 5) Declare the hostPath volume for audit-logs
- name: Declare audit-logs hostPath volume
  blockinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    marker: "# {mark} ANSIBLE AUDIT VOLUMES"
    insertafter: 'volumes:'
    block: |
      - name: audit-logs
        hostPath:
          path: /var/log/kubernetes/audit
          type: DirectoryOrCreate
  notify: Restart kubelet
