---
# Playbook to install Helm and Prometheus on a Kubernetes cluster
- name: Add Helm signing key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
  register: helm_key_result
  until: helm_key_result is succeeded
  retries: 3
  delay: 5

- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add Helm repository
  ansible.builtin.apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: helm-stable-debian

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: present
  register: helm_install_result

# Verify Helm is installed correctly
- name: Verify Helm installation
  ansible.builtin.command: helm version
  register: helm_version
  changed_when: false
  failed_when: helm_version.rc != 0

# Add Prometheus Helm repository
- name: Add Prometheus Helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
  register: helm_repo_add

- name: Add Grafana Helm repository
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts
  register: helm_repo_add


# Update Helm repositories
- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  changed_when: true
  register: helm_repo_update
  until: helm_repo_update is succeeded

- name: Install Prometheus using Helm
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    state: present
    namespace: monitoring
    create_namespace: true
    values:
      server:
        persistentVolume:
          storageClass: "standard"
          size: "10Gi"
          
- name: Install Grafana using Helm
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana/grafana
    state: present
    namespace: monitoring
    create_namespace: true
    values:
      persistence:
        enabled: true
        size: 10Gi
      admin:
        password: "admin"

- name: Install Loki + Promtail using Helm
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana/loki-stack
    state: present
    namespace: monitoring
    create_namespace: true
    values:
      loki:
        persistence:
          enabled: true
          size: 10Gi
      promtail:
        enabled: true
  register: loki_install