---
# 0) Prereqs: make sure yq (Go binary) and yamllint are available
- name: Ensure yq v4 and yamllint are installed
  apt:
    name:
      - curl        # to fetch yq
      - yamllint
    state: present
    update_cache: yes
  become: true

- name: Download Mike Farah's yq v4 if not present
  get_url:
    url: https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_linux_amd64
    dest: /usr/local/bin/yq
    mode: '0755'
  become: true
  args:
    creates: /usr/local/bin/yq

# 1) Make sure our audit log dir & policy file exist
- name: Create audit log directory
  file:
    path: /var/log/kubernetes/audit
    state: directory
    mode: '0700'
  become: true

- name: Copy audit policy to control-plane
  copy:
    src: audit-policy.yaml
    dest: /etc/kubernetes/audit-policy.yaml
    owner: root
    group: root
    mode: '0644'
  become: true

# 2) Clean out any old audit mounts/volumes
- name: Remove legacy audit‐policy mount if present
  command: >
    yq eval -i '
      with(.spec.containers[] | select(.name == "kube-apiserver"); 
        .volumeMounts |= map(select(.name != "audit-policy"))
      )
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true

- name: Remove legacy audit‐logs mount if present
  command: >
    yq eval -i '
      with(.spec.containers[] | select(.name == "kube-apiserver"); 
        .volumeMounts |= map(select(.name != "audit-logs"))
      )
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true

- name: Remove legacy audit‐policy volume if present
  command: >
    yq eval -i '
      .spec.volumes |= map(select(.name != "audit-policy"))
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true

- name: Remove legacy audit‐logs volume if present
  command: >
    yq eval -i '
      .spec.volumes |= map(select(.name != "audit-logs"))
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true

# 3) Insert the four blocks in the right place
- name: Add audit‐policy mount to kube‐apiserver
  command: >
    yq eval -i '
      (.spec.containers[] | select(.name == "kube-apiserver") .volumeMounts) +=
      [{"name":"audit-policy",
        "mountPath":"/etc/kubernetes/audit-policy.yaml",
        "subPath":"audit-policy.yaml",
        "readOnly":true}]
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true
  notify: Restart kubelet

- name: Add audit‐logs mount to kube‐apiserver
  command: >
    yq eval -i '
      (.spec.containers[] | select(.name == "kube-apiserver") .volumeMounts) +=
      [{"name":"audit-logs",
        "mountPath":"/var/log/kubernetes/audit",
        "readOnly":false}]
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true
  notify: Restart kubelet

- name: Add audit‐policy volume to kube‐apiserver
  command: >
    yq eval -i '
      .spec.volumes +=
      [{"name":"audit-policy",
        "hostPath":{"path":"/etc/kubernetes/audit-policy.yaml","type":"FileOrCreate"}}]
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true
  notify: Restart kubelet

- name: Add audit‐logs volume to kube‐apiserver
  command: >
    yq eval -i '
      .spec.volumes +=
      [{"name":"audit-logs",
        "hostPath":{"path":"/var/log/kubernetes/audit","type":"DirectoryOrCreate"}}]
    ' /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true
  notify: Restart kubelet

# 4) Lint the resulting manifest (80-char rule disabled)
- name: Lint kube-apiserver manifest (ignore line-length)
  command: >
    yamllint
      -d "{extends: default, rules: {line-length: disable}}"
      --strict --format parsable
      /etc/kubernetes/manifests/kube-apiserver.yaml
  register: lint_result
  failed_when: lint_result.rc != 0
  changed_when: false
  become: true

# 5) If lint passed, restart kubelet
- name: Restart kubelet to apply new kube-apiserver manifest
  service:
    name: kubelet
    state: restarted
  become: true
