---
# tasks/join_workers.yml
# — only runs on worker-group hosts

- name: Join the Kubernetes cluster
  command: "{{ hostvars[groups['master-node'][0]].join_command }}"
  args:
    creates: /etc/kubernetes/kubelet.conf