apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-data-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${PV_SIZE}
  storageClassName: ${PV_STORAGE_CLASS}