---
- hosts: jenkins-server
  become: true
  gather_facts: true
  vars_files:
    - host_vars/jenkins-ci.yml
    - group_vars/secrets.yml
    - group_vars/all.yml

  tasks:
  - name: Install Jenkins
    import_tasks: tasks/install_jenkins.yml
    tags: jenkins
    when: "'jenkins-server' in group_names"

  - name: Install Jenkins plugins
    import_tasks: tasks/install_extra_jenkins_settings.yml
    tags: jenkins
    when: "'jenkins-server' in group_names"
  
  - name: Install Docker
    import_tasks: tasks/install_docker.yml
    tags: docker
    when: "'jenkins-server' in group_names"

  - name: Setup Vault Development Container
    import_tasks: tasks/setup_vault.yml
    tags: vault
    when: "'jenkins-server' in group_names"

  handlers:
    - name: restart jenkins
      systemd:
        name: jenkins
        state: restarted

    - name: reload nginx
      service:
        name: nginx
        state: reloaded
