---
- hosts: all
  become: true
  vars:
    container_check_file: /tmp/container.txt

  tasks:
  - name: Install containerd
    import_tasks: tasks/containerd_setup.yml
    when: ubuntu_condition
    tags: containerd

  - name: Install monitoring tools
    import_tasks: tasks/install_monitoring.yml
    tags: monitoring

  - name: Install Kubernetes components
    import_tasks: 
      - tasks/setup_kubetools_pre_task.yml
      - tasks/setup_kubetools.yml
    tags: kubetools

  - name: Bootstrap master node
    import_tasks: tasks/bootstrap_master.yml
    when: "'master-node' in group_names"
    tags: kubernetes

  - name: Join worker nodes
    import_tasks: tasks/join_workers.yml
    when: "'worker-node' in group_names"
    tags: kubernetes
