apiVersion: apps/v1
kind: Deployment
metadata:
  name: lstm-model-deployment
  labels:
    app: lstm-model
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lstm-model
  template:
    metadata:
      labels:
        app: lstm-model
    spec:
      containers:
      - name: lstm-model
        image: freshinit/lstm-model:latest
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "/app/kubernetes_lstm_disaster_recovery(2).h5"
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lstm-model-service
  labels:
    app: lstm-model
  namespace: monitoring
spec:
  selector:
    app: lstm-model
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
 # type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lstm-model-config
  namespace: monitoring
data:
  MODEL_PATH: "/app/kubernetes_lstm_disaster_recovery(2).h5"